/*
 * generated by Xtext
 */
package org.xtext.example.assignment6.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConfiguratorDSLUiModule extends org.xtext.example.assignment6.ui.AbstractConfiguratorDSLUiModule {
	public ConfiguratorDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
