/**
 * generated by Xtext
 */
package org.xtext.example.assignment6.validation;

import org.xtext.example.assignment6.validation.AbstractConfiguratorDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ConfiguratorDSLValidator extends AbstractConfiguratorDSLValidator {
}
