/*
 * generated by Xtext
 */
package org.xtext.example.assignment6;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ConfiguratorDSLStandaloneSetup extends ConfiguratorDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new ConfiguratorDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

