/*
 * generated by Xtext
 */
package org.xtext.example.assignment6;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConfiguratorDSLRuntimeModule extends org.xtext.example.assignment6.AbstractConfiguratorDSLRuntimeModule {

}
