<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="req_spec" nsURI="http://chalmers.se/cse/se/2016/reqSpec" nsPrefix="req">
  <eClassifiers xsi:type="ecore:EClass" name="RequirementsSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" upperBound="-1"
        eType="#//Category" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="#//Description" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/reqResponsibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependsOn" upperBound="-1"
        eType="#//UnaryDependency" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//Requires" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="categoryName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subcategory" upperBound="-1"
        eType="#//Category" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" upperBound="-1"
        eType="#//Requirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/catResponsibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalRequirement" eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="QualityRequirement" eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Description">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptionText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catResponsibility" upperBound="-1"
        eType="#//Category" eOpposite="#//Category/responsible"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reqResponsibility" upperBound="-1"
        eType="#//Requirement" eOpposite="#//Requirement/responsible"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryDependency" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Requirement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICost" eSuperTypes="#//UnaryDependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="CValue" eSuperTypes="#//UnaryDependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="Refines" eSuperTypes="#//UnaryDependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="Requires">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="not" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftHand" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightHand" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//BinaryOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" lowerBound="1"
        eType="#//Requirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperator">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Requirement"/>
  </eClassifiers>
</ecore:EPackage>
