/*
 * generated by Xtext
 */
/*
 * generated by Xtext
 */
package org.xtext.example.assignment6.serializer;


class ConfiguratorDSLSyntacticSequencer extends AbstractConfiguratorDSLSyntacticSequencer {
}
