/*
 * generated by Xtext
 */
package org.xtext.example.assignment6.ui.contentassist

import org.xtext.example.assignment6.ui.contentassist.AbstractConfiguratorDSLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ConfiguratorDSLProposalProvider extends AbstractConfiguratorDSLProposalProvider {
}
