/*
 * generated by Xtext
 */
package org.xtext.example.assignment6;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ConfiguratorDSLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.example.assignment6.ui.internal.ConfiguratorDSLActivator.getInstance().getInjector("org.xtext.example.assignment6.ConfiguratorDSL");
	}
	
}
