/*
 * generated by Xtext
 */
package org.xtext.example.assignment6.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.assignment6.ui.internal.ConfiguratorDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConfiguratorDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ConfiguratorDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ConfiguratorDSLActivator.getInstance().getInjector(ConfiguratorDSLActivator.ORG_XTEXT_EXAMPLE_ASSIGNMENT6_CONFIGURATORDSL);
	}
	
}
