/*
 * generated by Xtext
 */
package org.xtext.example.assignment6.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ConfiguratorDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/example/assignment6/parser/antlr/internal/InternalConfiguratorDSL.tokens");
	}
}
