/**
 * generated by Xtext
 */
package org.xtext.example.assignment6.serializer;

import org.xtext.example.assignment6.serializer.AbstractConfiguratorDSLSemanticSequencer;

@SuppressWarnings("all")
public class ConfiguratorDSLSemanticSequencer extends AbstractConfiguratorDSLSemanticSequencer {
}
