/**
 * generated by Xtext
 */
package org.xtext.example.assignment6.serializer;

import org.xtext.example.assignment6.serializer.AbstractConfiguratorDSLSyntacticSequencer;

@SuppressWarnings("all")
public class ConfiguratorDSLSyntacticSequencer extends AbstractConfiguratorDSLSyntacticSequencer {
}
